---
- name: Auto Expand Subnets (Main)
  hosts: localhost
  gather_facts: no

  vars:
    threshold: 80                   # Utilization percentage trigger
    auto_base_prefix: 16            # Infer parent supernet as /16 from 1st two octets
    suffix_pattern: '-\\d{3}-snt$'  # Naming format: Region-env-sol-region-001-snt
    number_segment_len: 3           # 001 / 002 / 003 format

    # Regions where subnets may exist (add/remove as needed)
    regions:
      - asia-south1
      - asia-south2
      - asia-east1
      - asia-southeast1
      - asia-southeast2
      - us-central1
      - us-east1
      - us-east4
      - us-west1
      - europe-west1

  tasks:

    #################################################################
    #           1. READ **ALL** SUBNETS ACROSS ALL REGIONS
    #################################################################

    - name: Get subnets from all regions
      google.cloud.gcp_compute_subnetwork_info:
        project: "{{ gcp_project }}"
        region: "{{ item }}"
      loop: "{{ regions }}"
      register: subnet_info

    - name: Merge regional subnet results into one list
      set_fact:
        all_subnets:
          resources: "{{ subnet_info.results | map(attribute='resources') | flatten }}"

    - name: Extract all subnet names
      set_fact:
        all_names: "{{ all_subnets.resources | map(attribute='name') | list }}"

    #################################################################
    #      2. DISCOVER GROUP PREFIXES FROM NAMING PATTERN
    #################################################################

    - name: Derive group prefixes automatically
      set_fact:
        groups: >-
          {{
            all_names
            | map('regex_replace', suffix_pattern, '')
            | unique
            | reject('equalto','')
            | list
          }}

    - name: Debug detected subnet groups
      debug:
        msg: "Detected subnet groups: {{ groups }}"

    #################################################################
    #   3. PROCESS EACH GROUP USING expand_group.yml LOGIC
    #################################################################

    - name: Process each discovered group
      include_tasks: expand_group.yml
      loop: "{{ groups }}"
      loop_control:
        loop_var: group_name
      vars:
        all_subnets_info: "{{ all_subnets }}"
