---
- name: Auto expand subnet (Python wrapper)
  hosts: localhost
  gather_facts: no

  vars:
    gcp_project: network-automation-471112

  tasks:

    - name: Run Python IPAM logic
      command: >
        python3 expand_subnet.py {{ gcp_project }}
      register: py_out
      changed_when: false

    - name: Parse Python output
      set_fact:
        ipam: "{{ py_out.stdout | from_json }}"

    - name: Skip when nothing to do
      meta: end_play
      when: ipam.skip | default(false)

    - name: Fail if Python returned error
      fail:
        msg: "{{ ipam.error }}"
      when: ipam.error is defined

    - name: Create subnet
      google.cloud.gcp_compute_subnetwork:
        project: "{{ gcp_project }}"
        name: "{{ ipam.new_name }}"
        region: "{{ ipam.region }}"
        network: "{{ ipam.network }}"
        ip_cidr_range: "{{ ipam.cidr }}"

    - debug:
        msg: "Created subnet {{ ipam.new_name }} with {{ ipam.cidr }}"
