---
- name: Auto Expand Subnets (Main)
  hosts: localhost
  gather_facts: no

  vars:
    threshold: 80
    auto_base_prefix: 16
    suffix_pattern: '-\\d{3}-snt$'
    number_segment_len: 3

    # Only your required GCP regions
    regions:
      - asia-south1       # AO
      - europe-west1      # EU
      - asia-east1        # AS
      - us-central1       # NA

  tasks:

    ###########################################################################
    # 1) Fetch ALL subnets from the 4 allowed regions
    ###########################################################################

    - name: Get subnets from allowed regions
      google.cloud.gcp_compute_subnetwork_info:
        project: "{{ gcp_project }}"
        region: "{{ item }}"
      loop: "{{ regions }}"
      register: subnet_info

    - name: Merge subnet results
      set_fact:
        all_subnets:
          resources: "{{ subnet_info.results | map(attribute='resources') | flatten }}"

    - name: Extract all subnet names
      set_fact:
        all_names: "{{ all_subnets.resources | map(attribute='name') | list }}"

    ###########################################################################
    # 2) Auto-discover subnet groups (prefixes before -NNN-snt)
    #    FIX: renamed groups → subnet_groups (avoid AWX conflict)
    ###########################################################################

    - name: Auto-discover subnet group prefixes
      set_fact:
        subnet_groups: >-
          {{
            all_names
            | map('regex_replace', suffix_pattern, '')
            | unique
            | reject('equalto','')
            | list
          }}

    - name: Debug subnet groups
      debug:
        msg: "Detected subnet groups: {{ subnet_groups }}"

    ###########################################################################
    # 3) Process each group via expand_group.yml
    ###########################################################################

    - name: Process subnet group
      include_tasks: expand_group.yml
      loop: "{{ subnet_groups }}"
      loop_control:
        loop_var: group_name
      vars:
        all_subnets_info: "{{ all_subnets }}"
