---
- name: Auto Expand Subnets
  hosts: localhost
  gather_facts: no

  vars:
    threshold: 80
    auto_base_prefix: 16
    suffix_pattern: '-[0-9]{3}-snt$'

    regions:
      - asia-south1
      - europe-west1
      - asia-east1
      - us-central1

  tasks:

    - name: Get subnets from all regions
      google.cloud.gcp_compute_subnetwork_info:
        project: "{{ gcp_project }}"
        region: "{{ item }}"
      loop: "{{ regions }}"
      register: r

    - name: Flatten subnets
      set_fact:
        all_subnets:
          resources: "{{ r.results | map(attribute='resources') | flatten }}"

    - name: Extract names
      set_fact:
        all_names: "{{ all_subnets.resources | map(attribute='name') | list }}"

    - name: Detect group prefixes
      set_fact:
        subnet_groups: >-
          {{
            all_names 
            | select('search', suffix_pattern)
            | map('regex_replace', suffix_pattern, '')
            | unique
            | list
          }}

    - name: Show detected groups
      debug:
        msg: "{{ subnet_groups }}"

    - name: Process each group
      include_tasks: expand_group.yml
      loop: "{{ subnet_groups }}"
      loop_control:
        loop_var: group_name
      vars:
        all_subnets_info: "{{ all_subnets }}"
