- name: Auto-expand GCP subnet (jump host)
  hosts: 192.168.20.129
  gather_facts: no

  vars:
    gcp_sa_key: /etc/ansible/gcloud/sa.json

  tasks:
    - name: Run GCP auto expand
      gcp_suto_expand_free_ip:
        project: "{{ gcp_project }}"
