---
- name: Auto Expand Subnets (Main)
  hosts: localhost
  gather_facts: no

  vars:
    threshold: 80
    auto_base_prefix: 16
    suffix_pattern: '-\\d{3}-snt$'
    number_segment_len: 3

  tasks:

    - name: Get ALL subnets in the project
      google.cloud.gcp_compute_subnetwork_info:
        project: "{{ gcp_project }}"
      register: all_subnets

    - name: Extract all subnet names
      set_fact:
        all_names: "{{ all_subnets.resources | map(attribute='name') | list }}"

    - name: Derive group prefixes automatically
      set_fact:
        groups: >-
          {{
            all_names
            | map('regex_replace', suffix_pattern, '')
            | unique
            | reject('equalto','')
            | list
          }}

    - name: Debug groups found
      debug:
        msg: "Detected subnet groups: {{ groups }}"

    - name: Process each group
      include_tasks: expand_group.yml
      loop: "{{ groups }}"
      loop_control:
        loop_var: group_name
      vars:
        all_subnets_info: "{{ all_subnets }}"
