---
- name: Auto expand subnet (Python + Ansible)
  hosts: localhost
  gather_facts: no

  vars:
    gcp_project: network-automation-471112
    group_name: ao-np-api-asia-south1

  tasks:

    - name: Run Python IPAM logic
      command: >
        python3 scripts/expand_subnet.py
        {{ gcp_project }}
        {{ group_name }}
      register: py_out
      changed_when: false

    - name: Parse Python output
      set_fact:
        ipam: "{{ py_out.stdout | from_json }}"

    - name: Skip when no expansion needed
      meta: end_play
      when: ipam.skip | default(false)

    - name: Fail if Python returned error
      fail:
        msg: "{{ ipam.error }}"
      when: ipam.error is defined

    - name: Create new subnet
      google.cloud.gcp_compute_subnetwork:
        project: "{{ gcp_project }}"
        name: "{{ ipam.new_name }}"
        region: "{{ ipam.region }}"
        network: "{{ ipam.network }}"
        ip_cidr_range: "{{ ipam.cidr }}"

    - name: Success
      debug:
        msg: "Subnet {{ ipam.new_name }} created with {{ ipam.cidr }}"
