- name: Auto-expand GCP subnet 
  hosts: 192.168.20.129
  gather_facts: no

  vars:
    gcp_sa_key: /etc/ansible/gcloud

  tasks:
    - name: Activate GCP service account
      command: >
        gcloud auth activate-service-account
        --key-file={{ gcp_sa_key }}
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    - name: Set GCP project
      command: >
        gcloud config set project {{ gcp_project }}
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    - name: Run GCP auto expand
      gcp_auto_expand:
        project: "{{ gcp_project }}"
      register: expand_out

    - name: Show result
      debug:
        var: expand_out
