---
- name: Auto-expand GCP subnets (production)
  hosts: 192.168.65.129
  gather_facts: no
  connection: ssh
  become: no

  vars:
    py_script: /etc/ansible/Auto_expand/expand_subnet.py
    gcp_sa_key: /etc/gcloud/sa.json
    gcp_project: network-automation-471112

  tasks:

    - name: Verify service account key exists
      stat:
        path: "{{ gcp_sa_key }}"
      register: sa_stat

    - name: Fail if SA key missing
      fail:
        msg: "Service account key not found at {{ gcp_sa_key }}"
      when: not sa_stat.stat.exists

    - name: Activate GCP service account (non-interactive)
      command: >
        gcloud auth activate-service-account
        --key-file={{ gcp_sa_key }}
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    - name: Set GCP project
      command: >
        gcloud config set project {{ gcp_project }}
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    - name: Run IPAM auto-expand logic
      command: >
        python3 {{ py_script }} {{ gcp_project }}
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
      register: py_out

    - name: Show result
      debug:
        var: py_out.stdout
