- name: Auto-expand GCP subnet (custom module)
  hosts: 192.168.20.129
  gather_facts: no

  tasks:
    - name: Authenticate gcloud using AWX-injected SA
      command: >
        gcloud auth activate-service-account
        --key-file={{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}
      environment:
        CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
        
    - name: Run GCP auto expand
      gcp_auto_expand:
        project: "{{ gcp_project }}"
      register: expand_out

    - name: Show result
      debug:
        var: expand_out
